# Generated by Django 5.2.8 on 2025-12-01 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_employees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='mame',
            new_name='name',
        ),
    ]
